/**
 * Post-process the static export in `out/` for Cloudflare Pages.
 *
 * Runs automatically after `next build` (see package.json "build").
 *
 * 1. OG images get a `.png` extension.
 *    `next build` with `output: "export"` writes share cards as extension-less
 *    files (`/writing/foo/opengraph-image`). Cloudflare picks Content-Type from
 *    the extension, so those would be served as application/octet-stream and
 *    WeChat / X / Slack may refuse to render them. We rename every card to
 *    `opengraph-image.png` and rewrite the references in the HTML and in the
 *    RSC payloads (`*.txt`, used for client-side navigation).
 *
 * 2. `_headers` is generated from `config/security-headers.mjs` — the same
 *    source `next dev` uses — plus cache rules. A static export has no server,
 *    so this file is the only way headers reach production.
 *
 * The script fails the build loudly if anything it expects is missing, so a
 * Next.js upgrade that changes the export layout cannot ship silently broken.
 */
import fs from "node:fs";
import path from "node:path";

import { securityHeaders } from "../config/security-headers.mjs";

const OUT = path.resolve("out");

if (!fs.existsSync(OUT)) {
  console.error("postbuild: out/ not found — did `next build` run with output: \"export\"?");
  process.exit(1);
}

function walk(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(p));
    else files.push(p);
  }
  return files;
}

const all = walk(OUT);

// ── 1. OG images ───────────────────────────────────────────────────────────
const ogFiles = all.filter((f) => path.basename(f) === "opengraph-image");
if (ogFiles.length === 0) {
  console.error("postbuild: no opengraph-image files found in out/ — export layout changed?");
  process.exit(1);
}
for (const f of ogFiles) fs.renameSync(f, `${f}.png`);

// `/opengraph-image?hash` -> `/opengraph-image.png?hash` (the hash busts caches
// when the card changes). The negative lookahead keeps this idempotent.
const OG_REF = /\/opengraph-image(?![.\w-])/g;
let rewritten = 0;
for (const f of all) {
  if (!/\.(html|txt)$/.test(f)) continue;
  const src = fs.readFileSync(f, "utf8");
  if (!src.includes("/opengraph-image")) continue;
  const next = src.replace(OG_REF, "/opengraph-image.png");
  if (next !== src) {
    fs.writeFileSync(f, next);
    rewritten++;
  }
}

// ── 2. _headers ────────────────────────────────────────────────────────────
const block = (pattern, headers) =>
  [pattern, ...headers.map(([k, v]) => `  ${k}: ${v}`)].join("\n");

const headersFile = [
  "# Generated by scripts/postbuild.mjs — edit config/security-headers.mjs instead.",
  "# https://developers.cloudflare.com/pages/configuration/headers/",
  "",
  block(
    "/*",
    securityHeaders().map(({ key, value }) => [key, value]),
  ),
  "",
  "# Hashed build assets never change for a given URL.",
  block("/_next/static/*", [
    ["Cache-Control", "public, max-age=31536000, immutable"],
  ]),
  "",
  block("/hero-desk-*", [["Cache-Control", "public, max-age=2592000"]]),
  "",
  "# Share cards: cache a day at the edge; the ?hash in the URL busts it.",
  block("/opengraph-image.png", [["Cache-Control", "public, max-age=86400"]]),
  block("/*/opengraph-image.png", [["Cache-Control", "public, max-age=86400"]]),
  "",
  block("/rss.xml", [
    ["Content-Type", "application/rss+xml; charset=utf-8"],
    ["Cache-Control", "public, max-age=3600"],
  ]),
  "",
  "# Fetched by the ⌘K dialog; must not be indexed.",
  block("/search-index.json", [
    ["Cache-Control", "public, max-age=300"],
    ["X-Robots-Tag", "noindex"],
  ]),
  "",
  "# Preview deployments (*.pages.dev) must not compete with the real domain.",
  block("https://:project.pages.dev/*", [["X-Robots-Tag", "noindex"]]),
  "",
].join("\n");

fs.writeFileSync(path.join(OUT, "_headers"), headersFile);

console.log(
  `postbuild: ${ogFiles.length} OG images → .png, ${rewritten} files rewritten, _headers written`,
);
